# permissions for end users to edit mymobilecorenwkinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mymobilecorenwkind-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mymobilecorenw
    app.kubernetes.io/part-of: mymobilecorenw
    app.kubernetes.io/managed-by: kustomize
  name: mymobilecorenwkind-editor-role
rules:
- apiGroups:
  - mobilecoregrp.my.domain
  resources:
  - mymobilecorenwkinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobilecoregrp.my.domain
  resources:
  - mymobilecorenwkinds/status
  verbs:
  - get
