---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mobilecoregrp.my.domain
  resources:
  - mymobilecorenwkinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobilecoregrp.my.domain
  resources:
  - mymobilecorenwkinds/finalizers
  verbs:
  - update
- apiGroups:
  - mobilecoregrp.my.domain
  resources:
  - mymobilecorenwkinds/status
  verbs:
  - get
  - patch
  - update
